### ISSUE TITLE
DNX support

### ISSUE THREAD

**Issue by ganeshran** [nosami/grunt-init-csharpsolution#1]
Is it possible to provide dnx support for the new .NET runtime? 

Instead of a solution, the dependencies are specified in a global.json file at solution root level and project.json for each individual project.

**Comment by ganeshran** [comment]
Closing this issue since the last commit was over an year ago and doesn't look like the repo is being actively maintained.

**Comment by nosami** [comment]
You should use this instead - https://github.com/OmniSharp/generator-aspnet

**Comment by ganeshran** [comment]
@nosami Thanks I'll use that repo instead.
